#.\EnableWindowsSubsystemLinux.ps1
#.\EnableExecution.ps1
#.\remove-default-apps.ps1
#.\install-basic-software.ps1
#.\installPkgMngrs.ps1
#.\setup1.ps1
.\install-software.ps1
#.\Install-Chocolatey.ps1
#.\Install_Software.ps1